
# 1. 为工作流定义名字
name: Deploy VitePress site to Pages
# 2. 触发条件修改为: 当 main 或 master 分支, 有 push 的时候, 执行任务
on:
  push:
    branches:
      - main
    # tags:
    #   - '*'

  # workflow_dispatch:
# 3. 创建工作流
jobs:
  # 工作流名称
  deploy-and-sync:
    # 依赖环境
    runs-on: ubuntu-latest
    steps:
      # step 1. 获取源码, 拉取仓库代码
      # 步骤名
      - name: Checkout 🛎️
        # 使用插件 => https://github.com/actions/checkout
        uses: actions/checkout@v4
        # 插件携带参数
        # with:
        #   ref: 'master'
      # step 2. 使用指定版本 node
      - name: Install yarn
        run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      # step 3. 安装依赖并打包
      - name: Install dependencies
        run: yarn install

      - name: Build Site
        run: npm run docs:build

      # step 4. 项目部署, 将打包后的产物合并到指定的分支上
      - name: Deploy for GitHub 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist
          # enable single-commit to reduce the repo size
          single-commit: true
          clean: true

      # - name: Sync to Gitee
      #   uses: wearerequired/git-mirror-action@v1.2.0
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      #   with:
      #     # GitHub 仓库地址
      #     source-repo: git@github.com:Moonofweisheng/uni-mini-router.git
      #     # Gitee 仓库地址
      #     destination-repo: git@gitee.com:Moonofweisheng/uni-mini-router.git
  
      # - name: Build Gitee Pages
      #   uses: yanglbme/gitee-pages-action@main
      #   with:
      #     # 替换为你的 Gitee 用户名
      #     gitee-username: Moonofweisheng
      #     # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
      #     gitee-password: ${{ secrets.GITEE_PASSWORD }}
      #     # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
      #     gitee-repo: Moonofweisheng/uni-mini-router
      #     # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
      #     branch: gh-pages

